### ISSUE TITLE
Importing this into another project, I get an fs error

### ISSUE THREAD

**Issue by kkgthb** [brob/eleventy-plugin-podcast-tools#9]
Even trying copying your sample `index.njk` and `audio-file.m4a` into my own project, I keep getting errors with `fs`.

```sh
Unhandled rejection in promise ([object Promise]): (more in DEBUG output)
> ENOENT: no such file or directory, stat './media/audio-file.m4a'

`Error` was thrown:
    Error: ENOENT: no such file or directory, stat './media/audio-file.m4a'
        at Object.statSync (node:fs:1142:3)
        at Context.module.exports (C:\example\node_modules\eleventy-plugin-podcast-tools\src\filesize.js:4:22)
        at Context.<anonymous> (C:\example\node_modules\@11ty\eleventy\src\BenchmarkGroup.js:30:26)
        at eval (eval at _compile (C:\example\node_modules\nunjucks\src\environment.js:633:18), <anonymous>:14:59)
        at Context.<anonymous> (C:\example\node_modules\eleventy-plugin-podcast-tools\.eleventy.js:12:13)   
```

**Comment by kkgthb** [comment]
Nevermind, turns out you didn't have a src folder and I did.  Problem solved.
